# Generated by Django 5.2.16 on 2026-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='projects', to='auth.group'),
        ),
    ]
