# Generated by Django 5.2.16 on 2026-07-27 12:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('error_context', models.JSONField(default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('queued', 'Queued'),
                            ('indexing', 'Indexing'),
                            ('analyzing', 'Analyzing'),
                            ('bug_localization', 'Bug Localization'),
                            ('rca', 'Rca'),
                            ('patching', 'Patching'),
                            ('validating', 'Validating'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                        ],
                        default='queued',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='analyses',
                        to='projects.project',
                    ),
                ),
                (
                    'repository',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='analyses',
                        to='repositories.repository',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='analyses',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('step', models.CharField(max_length=50)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('running', 'Running'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                            ('skipped', 'Skipped'),
                        ],
                        default='running',
                        max_length=20,
                    ),
                ),
                ('input', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                (
                    'analysis',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='runs',
                        to='analyses.analysis',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BugLocalization',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'analysis',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bug_localization',
                        to='analyses.analysis',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('diff', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('applied', 'Applied'),
                            ('validated', 'Validated'),
                            ('rejected', 'Rejected'),
                            ('error', 'Error'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'analysis',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patch',
                        to='analyses.analysis',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PatchValidation',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_failed', models.IntegerField(default=0)),
                ('tests_skipped', models.IntegerField(default=0)),
                ('lint_errors', models.IntegerField(default=0)),
                ('lint_warnings', models.IntegerField(default=0)),
                ('type_errors', models.IntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('output_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'patch',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='validation',
                        to='analyses.patch',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('markdown', models.TextField()),
                (
                    'format',
                    models.CharField(
                        choices=[('markdown', 'Markdown'), ('pdf', 'Pdf'), ('html', 'Html')],
                        default='markdown',
                        max_length=10,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'analysis',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='report',
                        to='analyses.analysis',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('summary', models.TextField()),
                ('root_file', models.CharField(max_length=1024)),
                ('root_line', models.IntegerField(blank=True, null=True)),
                ('cause_chain', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'analysis',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='root_cause',
                        to='analyses.analysis',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousFileScore',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('file_path', models.CharField(max_length=2048)),
                ('suspicion_score', models.FloatField()),
                ('matched_lines', models.JSONField(default=list)),
                ('evidence', models.TextField(blank=True, default='')),
                ('rank', models.IntegerField()),
                (
                    'localization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='suspicious_files',
                        to='analyses.buglocalization',
                    ),
                ),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
