# Generated by Django 5.2.16 on 2026-07-29 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_add_vector_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('indexing', 'Indexing'), ('analyzing', 'Analyzing'), ('bug_localization', 'Bug Localization'), ('rca', 'Rca'), ('patching', 'Patching'), ('validating', 'Validating'), ('fix_suggestion', 'Fix Suggestion'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='FixSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff', models.TextField(blank=True, default='')),
                ('plan', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fix_suggestion', to='analyses.analysis')),
            ],
        ),
    ]
