# Generated by Django 5.2.16 on 2026-07-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_alter_analysis_status_fixsuggestion'),
        ('repositories', '0002_repository_assigned_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='repositories',
            field=models.ManyToManyField(blank=True, related_name='analysis_records', to='repositories.repository'),
        ),
    ]
