# Generated by Django 5.2.16 on 2026-08-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analyses', '0004_analysis_repositories'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='parent_analysis',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='analyses.analysis',
            ),
        ),
    ]
