# Generated by Django 5.2.17 on 2026-09-10 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0006_alter_analysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buglocalization',
            name='ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buglocalization',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buglocalization',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buglocalization',
            name='model_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buglocalization',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='buglocalization',
            name='watermark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='model_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='watermark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='model_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='report',
            name='watermark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='model_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='watermark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
