include /etc/ldap/schema/core.schema
include /etc/ldap/schema/cosine.schema
include /etc/ldap/schema/inetorgperson.schema
include /etc/ldap/schema/nis.schema

pidfile /run/slapd/slapd.pid
argsfile /run/slapd/slapd.args

modulepath /usr/lib/ldap
moduleload back_mdb

database mdb
maxsize 1073741824
suffix "dc=codecoroner,dc=dev"
rootdn "cn=admin,dc=codecoroner,dc=dev"
rootpw adminpass123
directory /var/lib/ldap
index objectClass eq