# Generated by Django 5.2.16 on 2026-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('model_tier', models.CharField(choices=[('fast', 'Veloce'), ('balanced', 'Equilibrato'), ('precise', 'Preciso')], default='balanced', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform setting',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
