from .base import *

DEBUG = False

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
    'user': os.environ.get('RATE_LIMIT_USER', '100/hour'),
    'anon': os.environ.get('RATE_LIMIT_ANON', '10/hour'),
}

LOGGING['root']['level'] = 'WARNING'
LOGGING['root']['handlers'] = ['console_json', 'app_file']
