# Generated by Django 5.2.16 on 2026-07-27 12:32

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedFile',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('file_path', models.CharField(max_length=2048)),
                ('language', models.CharField(max_length=50)),
                ('file_hash', models.CharField(max_length=64)),
                ('ast_nodes', models.JSONField(default=dict)),
                ('last_indexed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'chunk_type',
                    models.CharField(
                        choices=[
                            ('function', 'Function'),
                            ('class', 'Class Def'),
                            ('method', 'Method'),
                            ('block', 'Block'),
                            ('module', 'Module'),
                            ('docstring', 'Docstring'),
                        ],
                        max_length=50,
                    ),
                ),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('content', models.TextField()),
                ('tokens_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'parent_chunk',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='child_chunks',
                        to='repositories.codechunk',
                    ),
                ),
                (
                    'file',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='code_chunks',
                        to='repositories.indexedfile',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('model', models.CharField(default='nomic-embed-text', max_length=100)),
                ('dimensions', models.IntegerField(default=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'chunk',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='embedding',
                        to='repositories.codechunk',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('git_url', models.CharField(max_length=2048)),
                ('git_branch', models.CharField(default='main', max_length=255)),
                ('local_path', models.CharField(blank=True, max_length=1024, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('cloning', 'Cloning'),
                            ('indexing', 'Indexing'),
                            ('indexed', 'Indexed'),
                            ('error', 'Error'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('file_count', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='repositories',
                        to='projects.project',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='indexedfile',
            name='repository',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='indexed_files',
                to='repositories.repository',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='indexedfile',
            unique_together={('repository', 'file_path')},
        ),
    ]
