# Generated by Django 5.2.16 on 2026-07-29 16:40

import django.db.models.deletion
from django.db import migrations, models


def copy_project_to_assigned(apps, _schema_editor):  # noqa: ARG001
    Repository = apps.get_model('repositories', 'Repository')
    for repo in Repository.objects.exclude(project__isnull=True):
        repo.assigned_projects.add(repo.project)


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='assigned_projects',
            field=models.ManyToManyField(
                blank=True, related_name='assigned_repositories', to='projects.project'
            ),
        ),
        migrations.AlterField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='repositories',
                to='projects.project',
            ),
        ),
        migrations.RunPython(copy_project_to_assigned, reverse_code=migrations.RunPython.noop),
    ]
