# Generated by Django 5.2.16 on 2026-07-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
