# Generated by Django 5.2.16 on 2026-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('repositories', '0002_repository_assigned_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='repositories', to='auth.group'),
        ),
    ]
