# Generated by Django 5.2.16 on 2026-07-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_error_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'repositories'},
        ),
    ]
