# Generated by Django 5.2.17 on 2026-08-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_repository_auto_pull'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
